"""initial migration

Revision ID: 47432868eef1
Revises: 
Create Date: 2021-06-12 04:15:22.809607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47432868eef1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
